import { Crown, Gem, Sparkles, Star } from "lucide-react"

export const pricingEnglish = [
  {
    plan: "Shopdoora Lite",
    price: "$19/month",
    description: "Basic features for small businesses",
    icon: Star,
    iconCn: "dark:bg-gray-200 bg-gray-50 text-gray-700",
    features: [
      "1% Transaction fee based on revenue",
      "2 Staff accounts",
      "Maximum upload of 100 products",
      "Android Seller and Buyer Apps",
      "Payment Gateway Integration",
      "Member Points System",
    ],
  },
  {
    plan: "Shopdoora Standard",
    price: "$49/month",
    description: "Ideal for growing businesses with more features",
    icon: Sparkles,
    iconCn: "dark:bg-pink-200 bg-pink-100 text-pink-700",
    features: [
      "1% Transaction fee based on revenue",
      "5 Staff accounts",
      "Maximum upload of 500 products",
      "Android and iOS Seller and Buyer Apps",
      "Responsive Website for Buyers",
      "Payment Gateway Integration",
    ],
  },
  {
    plan: "Shopdoora Pro",
    price: "$99/month",
    description: "Advanced features for established businesses",
    icon: Gem,
    iconCn: "dark:bg-indigo-200 bg-indigo-100 text-indigo-800",
    features: [
      "1% Transaction fee based on revenue",
      "Unlimited staff accounts",
      "Unlimited product upload",
      "Android and iOS Seller and Buyer Apps",
      "Responsive Website for Buyers",
      "Administration Website for Sellers",
    ],
  },
  {
    plan: "Shopdoora Enterprise",
    price: "Contact Us",
    description: "Customized solutions for large enterprises",
    icon: Crown,
    iconCn: "dark:bg-sky-200 bg-sky-100 text-sky-700",
    features: [
      "No additional transaction fees",
      "Unlimited staff accounts",
      "Unlimited product upload",
      "Android and iOS Seller and Buyer Apps",
      "Responsive Website for Buyers",
      "Administration Website for Sellers",
    ],
  },
]

export const pricingBurmese = [
  {
    plan: "Shopdoora Lite",
    price: "$19/month",
    description: "Basic features for small businesses",
    icon: Star,
    iconCn: "dark:bg-gray-200 bg-gray-50 text-gray-700",
    features: [
      "1% Transaction fee based on revenue",
      "2 Staff accounts",
      "Maximum upload of 100 products",
      "Android Seller and Buyer Apps",
      "Payment Gateway Integration",
      "Member Points System",
    ],
  },
  {
    plan: "Shopdoora Standard",
    price: "$49/month",
    description: "Ideal for growing businesses with more features",
    icon: Sparkles,
    iconCn: "dark:bg-pink-200 bg-pink-100 text-pink-700",
    features: [
      "1% Transaction fee based on revenue",
      "5 Staff accounts",
      "Maximum upload of 500 products",
      "Android and iOS Seller and Buyer Apps",
      "Responsive Website for Buyers",
      "Payment Gateway Integration",
    ],
  },
  {
    plan: "Shopdoora Pro",
    price: "$99/month",
    description: "Advanced features for established businesses",
    icon: Gem,
    iconCn: "dark:bg-indigo-200 bg-indigo-100 text-indigo-800",
    features: [
      "1% Transaction fee based on revenue",
      "Unlimited staff accounts",
      "Unlimited product upload",
      "Android and iOS Seller and Buyer Apps",
      "Responsive Website for Buyers",
      "Administration Website for Sellers",
    ],
  },
  {
    plan: "Shopdoora Enterprise",
    price: "Contact Us",
    description: "Customized solutions for large enterprises",
    icon: Crown,
    iconCn: "dark:bg-sky-200 bg-sky-100 text-sky-700",
    features: [
      "No additional transaction fees",
      "Unlimited staff accounts",
      "Unlimited product upload",
      "Android and iOS Seller and Buyer Apps",
      "Responsive Website for Buyers",
      "Administration Website for Sellers",
    ],
  },
]
